name=analysis-korean
description=Korean morphology analyzer from LeeYudok/lucene-Korean-Analyzer
version=1.0.0
opensearch.version=3.7.0
java.version=21
classname=com.tistory.devyongsik.opensearch.KoreanAnalysisPlugin
has.native.controller=false
